global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: chrono-prod
    team: platform
    env: production

rule_files:
  - "prometheus-recording-rules.yml"

scrape_configs:
  - job_name: "job-producer"
    metrics_path: "/actuator/prometheus"
    relabel_configs:
      - target_label: application
        replacement: "chrono-queue"
      - source_labels: [ service ]
        target_label: service
      - target_label: env
        replacement: "production"
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ "job-producer:8081" ]
        labels:
          service: "job-producer"

  - job_name: "job-worker"
    metrics_path: "/actuator/prometheus"
    relabel_configs:
      - target_label: application
        replacement: "chrono-queue"
      - source_labels: [ service ]
        target_label: service
      - target_label: env
        replacement: "production"
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ "job-worker:8082" ]
        labels:
          service: "job-worker"

  - job_name: "retry-dispatcher"
    metrics_path: "/actuator/prometheus"
    relabel_configs:
      - target_label: application
        replacement: "chrono-queue"
      - source_labels: [ service ]
        target_label: service
      - target_label: env
        replacement: "production"
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ "retry-dispatcher:8083" ]
        labels:
          service: "retry-dispatcher"

  - job_name: "dlq-service"
    metrics_path: "/actuator/prometheus"
    relabel_configs:
      - target_label: application
        replacement: "chrono-queue"
      - source_labels: [ service ]
        target_label: service
      - target_label: env
        replacement: "production"
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ "dlq:8084" ]
        labels:
          service: "dlq-service"

  - job_name: "kafka-jmx-exporter"
    relabel_configs:
      - target_label: application
        replacement: "chrono-queue"
      - target_label: env
        replacement: "production"
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ "kafka-jmx-exporter:5556" ]
        labels:
          service: "kafka-broker"

  - job_name: "mongodb-exporter"
    relabel_configs:
      - target_label: application
        replacement: "chrono-queue"
      - target_label: env
        replacement: "production"
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ "mongodb-exporter:9216" ]
        labels:
          service: "mongodb"

  - job_name: "redis-exporter"
    relabel_configs:
      - target_label: application
        replacement: "chrono-queue"
      - source_labels: [ service ]
        target_label: service
      - target_label: env
        replacement: "production"
      - source_labels: [ __address__ ]
        target_label: instance
    static_configs:
      - targets: [ "redis-exporter:9121" ]
        labels:
          service: "redis"
