package com.chrono.common.api;

public enum ErrorCode {
    INVALID_REQUEST,
    VALIDATION_FAILED,
    JOB_PUBLISH_FAILED,
    SERIALIZATION_FAILED,
    JOB_NOT_FOUND,
    JOB_PROCESSING_FAILED,
    RETRY_SCHEDULING_FAILED,
    DLQ_PERSISTENCE_FAILED,
    INTERNAL_ERROR
}