# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
# Application Configuration
spring.application.name=job-producer
server.port=8081
# Logging Configuration
logging.level.root=INFO
logging.level.com.chrono.producer=INFO