# Kafka configuration
kafka.bootstrap-servers=localhost:9092
kafka.topic.job-events=job-events

# Application Configuration
spring.application.name=job-producer
server.port=8081


# Logging Configuration
logging.level.root=INFO
logging.level.com.chrono.producer=INFO