# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.job-events=job-events
# Application Configuration
spring.application.name=job-worker
server.port=8082
# Logging Configuration
logging.level.root=INFO
logging.level.com.chrono.worker=INFO